### ISSUE TITLE
no matches for kind "NamespaceScanner"

### ISSUE THREAD

**Issue by sys-ops** [devopstales/trivy-operator#1]
$ helm install --dry-run trivy-operator .
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "NamespaceScanner" in version "trivy-operator.devopstales.io/v1"

Possibly missing a CRD?

**Comment by devopstales** [comment]
Yes the operator create the CRD but when the helm tries to create the NamespaceScanner it is not created yet.

**Comment by bob-rohan** [comment]
I had a similar issue from deploying with `flux`.

I found more issues when I forked to resolve that issue. Seemed to trip up over namespaces which are missing any labels, and some of the loops were not right from what I can tell.

I've started to patch some of it on fork, work in progress but it's now working mostly.

**Comment by devopstales** [comment]
@bob-rohan You have the same problem with `flux` as I have with halm `helm`. I solved this chicken and egg problem in my helm chart wit adding the CRD in the chart. As I can see in your forked repo You did the same thing. I didn't see any other changes in your repo. So i didn't know what  "other issues" are you referring to, but BRs are welcomed, and if you have a specific problem please create a proper issue for it.

**Comment by bob-rohan** [comment]
Sure thing, will do
