### ISSUE TITLE
Support for using cluster pullsecrets

### ISSUE THREAD

**Issue by githubcdr** [devopstales/trivy-operator#19]
Hi,

First of all, thanks for trivy-operator :)

Would it be possible to use existing pullsecrets configured for this cluster to do image scanning?

**Comment by devopstales** [comment]
Hi @githubcdr

At the moment it is not possible to use pull secret for scanning. The pull secrets are used by kubernetes to pull an image, but in my case trivy needs to pull the images. Trivy is running in the operator's pod so for that to work I need to mount all the pull secrets to this pod. Or I can  list this secret from the kubernetes api but didn't see how can it fin them, and it need permission to all the pull secret in all the namespaces. This is problematic. 

Instead I use the `NamespaceScanner` CRD for the registry authentication configuration. I see your pint tat this `NamespaceScanner` is not stored as secret, but the secrets can be decoded if you have permission for that namespace. The default config is to store the secrets in etcd in plain text so i didn't thin it as a gouge risk.

**Comment by devopstales** [comment]
@githubcdr I intend to work on this in the 2.5 release.

**Comment by githubcdr** [comment]
I'm currently using trivy-operator by Aqua so closed this issue

**Comment by devopstales** [comment]
closed by https://github.com/devopstales/trivy-operator/commit/eab13ff3648692f4743962c65f20cd568da9312a
