### ISSUE TITLE
RFE: Offline usage trigger

### ISSUE THREAD

**Issue by evgkrsk** [devopstales/trivy-operator#28]
It may be usefull to run trivy-operator in offline (air-gapped) environment.

But now trivy-operator always fetch trivy db on startup ("startup_fn_trivy_cache" function) and during runtime.

I think that it is difficult to embrace all variants of offline envs in real-life, so my suggestion for now is simple: it is possible to implement completely offline trivy usage trigger? Idea is to leave db update up to sysadmin.

Official documentation may be good starting point: https://aquasecurity.github.io/trivy/v0.31.3/docs/advanced/air-gap/

**Comment by devopstales** [comment]
Hi @evgkrsk  

Thank you for using my trivy-operator. It is an interesting function. I think it is a fairly simple to add an option for offline scan in the CRD. Based on that it can disable the vulndb download at the beginning and add offline scan option to trivy run. If you want to help in that  pull requests are welcomed.

I will try to check on this this in the next release. I plan to release the 2.5 release at the end of September.

**Comment by evgkrsk** [comment]
Not sure if offline-scan is attribute of CRD. trivy-operator's deployment in k8s have internet access to update DB or don't have it. So, effectively all CRD objects are offline or online.

But surely you have better understanding of project's internals.

**Comment by devopstales** [comment]
@evgkrsk There is an option for trivy to use your docker registry for viln-db storage:

```
DB Flags
      --db-repository string   OCI repository to retrieve trivy-db from (default "ghcr.io/aquasecurity/trivy-db")
      --download-db-only       download/update vulnerability database but don't run a scan
      --no-progress            suppress progress bar
      --reset                  remove all caches and database
      --skip-db-update         skip updating vulnerability database
```

**Comment by evgkrsk** [comment]
Yes, it is one of possible ways to deliver fresh trivy db. It may be handy for some users to have ability to override ghcr.io OCI repo in trivy-operator.

**Comment by devopstales** [comment]
@evgkrsk in the [53e915e](https://github.com/devopstales/trivy-operator/commit/53e915edc57b409463f45944eb6c4a7de608481b) I added the ability to use custom OCI repo. I need to test of course but with that I think this feature is done.
