### ISSUE TITLE
How to set TRIVY_INSECURE to NamespaceScanner custom resource

### ISSUE THREAD

**Issue by javaflavor** [devopstales/trivy-operator#29]
I want to set CLI option TRIVY_INSECURE=true to NamespaceScanner.
Is it possible?

Thanks.

**Comment by devopstales** [comment]
Hi @javaflavor 

Thank you for using my trivy-operator. To answer your question there is no option at the moment to do that. It is a fairly simple think to do. I will try to solve this in the next release. I plan to release the 2.5 release at the end of September.

**Comment by javaflavor** [comment]
Hi @devopstales 

Thank you for your quick answer!
I will track this issue and the next release.

**Comment by devopstales** [comment]
closed by https://github.com/devopstales/trivy-operator/commit/254328be4c696ff6f9849f6f53d803b745b2b86b
