### ISSUE TITLE
Trivy operator reached the pull rate limit of docker.io

### ISSUE THREAD

**Issue by FogDong** [devopstales/trivy-operator#35]
**Describe the bug**
```
[2022-09-30 07:20:30,444] kopf.objects         [ERROR   ] [trivy-system/trivy-system-trivy-system-helm-trivy-operator-main-config] TRIVY ERROR: return 1
[2022-09-30 07:20:30,444] kopf.objects         [ERROR   ] [trivy-system/trivy-system-trivy-system-helm-trivy-operator-main-config] You have reached your pull rate limit.
```

It's quite easy the reach the rate limit of docker.io, will trivy-operator use the image from the machine other than pull the image from the docker registry?

**Expected behavior**

**Configuration file**

**Helm Values file**
Default helm values.

**Environment:**

- Trivy-Operator version (use `trivy-operator version`): trivy image: 2.4.1
- Installation type (Helm, Kubernetes, OperatorFramework): Helm: 2.4.3
- Kubernetes version (use `kubectl version`): v1.21.10
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

**Additional context**

**Comment by devopstales** [comment]
Hi @FogDong.

The trivy-operator use trivy in a container to scan images. It dose not reach the files on the host. Mounting the containerd/docker socket and folders to a container is a very unsecure thing . If you have a user in docker you can extend your pull rate limit. trivy-operator can use pull secret or username/passwor to authenticate with docker.io.
