### ISSUE TITLE
Please archive this repository

### ISSUE THREAD

**Issue by bo0ts** [devopstales/trivy-operator#44]
Please archive this unmaintained repository and remove it from the openshift marketplace so people don't install it accidentally or mistake it for the `aquasecurity/trivy-operator`.

**Comment by devopstales** [comment]
Hi @bo0ts 

The repository is not unmaintained. I am maintaining it alone in my free time and yes not allays pushing the changes to the feature branch. I understand that some people confuse my solution with aquasecurity's but to be clear I created a trivy-operator earlier. That time their solution was called starboard than they renamed to the same name I  already used.
